name: fake_terminal
description: A customizable fake terminal widget for Flutter applications.
version: 0.0.9
homepage: https://github.com/peoplesdriver/fake_terminal
repository: https://github.com/peoplesdriver/fake_terminal

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
