name: fake_terminal
description: A customizable fake terminal widget for Flutter applications.
version: 0.0.6
homepage: https://github.com/peoplesdriver/fake_terminal
repository: https://github.com/peoplesdriver/fake_terminal

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
